#!/usr/bin/bash

#start swwww
swww query || swww init

#if [[ $# -lt 1 ]] || [[ ! -d $1   ]]; then
#	echo "Usage:
#	$0 <dir containg images>"
#	exit 1
#fi

# Edit bellow to control the images transition
export SWWW_TRANSITION_FPS=60
export SWWW_TRANSITION_STEP=20

# This controls (in seconds) when to switch to the next image
INTERVAL=300

# swww img ~/wallpaper/68.png
# sleep INTERVAL

while true; do
	find "$1" \
		| while read -r img; do
			echo "$((RANDOM % 1000)):$img"
		done \
		| sort -n | cut -d':' -f2- \
		| while read -r img; do
			swww img "$img"
			sleep $INTERVAL
		done
done
