#!/bin/bash

#the main packages
install_stage=(
    # Basic softwares
    hyprland
    hyprlock
    waybar
    mako
    rofi-lbonn-wayland-git
    xorg-xwayland
    openssh
    # Terminal
    kitty
    fish
    starship
    # Network manager
    nm-connection-editor
    # Boswer
    firefox
    # Fonts
    ttf-sourcecodepro-nerd
    adobe-source-han-serif-cn-fonts
    wqy-zenhei
    noto-fonts 
    noto-fonts-cjk 
    noto-fonts-emoji 
    noto-fonts-extra
    # Audio
    pulseaudio
    sof-firmware
    alsa-firmware
    alsa-ucm-conf
    pavucontrol
    # Blue tooth 
    bluez
    bluez-utils
    blueman
    # Chinese input method
    fcitx5
    fcitx5-configtool
    fcitx5-gtk
    fcitx5-qt
    fcitx5-chinese-addons
    fcitx5-material-color
    # Intel GPU driver
    lib32-mesa
    vulkan-intel
    lib32-vulkan-intel
    # Screenshot
    grim
    slurp
    swappy
    # Clipboard history
    wl-clipboard
    cliphist
    # GTK theme
    lxappearance
    materia-gtk-theme
    papirus-icon-theme
    # QT theme
    qt5ct qt5-wayland
    #File manager
    thunar
    #Picture Viewer
    ristretto
    # Login starter
    sddm
    # Wallpaper manager
    swww
    # Others
    btop
    # Auto mount flash disk
    udiskie
    # Sddm theme
    qt6-5compat
    qt6-declarative
    qt6-svg
    # Calculator
    qalculate-qt
    # Music player
    yesplaymusic
    # File share
    samba
    # useful tools
    eza
)

for str in ${myArray[@]}; do
  echo $str
done

# set some colors
CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"
INSTLOG="install.log"

######
# functions go here

# function that would show a progress bar to the user
show_progress() {
    while ps | grep $1 &> /dev/null;
    do
        echo -n "."
        sleep 2
    done
    echo -en "Done!\n"
    sleep 2
}

# function that will test for a package and if not found it will attempt to install it
install_software() {
    # First lets see if the package is there
    if yay -Q $1 &>> /dev/null ; then
        echo -e "$COK - $1 is already installed."
    else
        # no package found so installing
        echo -en "$CNT - Now installing $1 ."
        yay -S --noconfirm $1 &>> $INSTLOG &
        show_progress $!
        # test to make sure package installed
        if yay -Q $1 &>> /dev/null ; then
            echo -e "\e[1A\e[K$COK - $1 was installed."
        else
            # if this is hit then a package is missing, exit to review log
            echo -e "\e[1A\e[K$CER - $1 install had failed, please check the install.log"
            exit
        fi
    fi
}

# clear the screen
clear

# set some expectations for the user
echo -e "$CNT - You are about to execute a script that would attempt to setup Hyprland.
Please note that Hyprland is still in Beta."
sleep 1

# let the user know that we will use sudo
echo -e "$CNT - This script will run some commands that require sudo. You will be prompted to enter your password.
If you are worried about entering your password then you may want to review the content of the script."
sleep 1

# give the user an option to exit out
read -rep $'[\e[1;33mACTION\e[0m] - Would you like to continue with the install (y,n) ' CONTINST
if [[ $CONTINST == "Y" || $CONTINST == "y" ]]; then
    echo -e "$CNT - Setup starting..."
    sudo touch /tmp/hyprv.tmp
else
    echo -e "$CNT - This script will now exit, no changes were made to your system."
    exit
fi

#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
	echo -e "$COK - yay was located, moving on."
else
	echo -e "$CWR - Yay was NOT located"
	read -n1 -rep $'[\e[1;33mACTION\e[0m] - Would you like to install yay (y,n) ' INSTYAY
	if [[ $INSTYAY == "Y" || $INSTYAY == "y" ]]; then
		sudo cp pacman.conf /etc/
		sudo pacman-key --lsign-key "farseerfc@archlinux.org"
		sudo pacman -Sy archlinuxcn-keyring
		sudo pacman -Su
		sudo pacman -S yay
		yay -Syyu
		if [ -f "$ISYAY" ]; then
			echo -e "$COK - yay was installed successfully."
		else
			echo -e "$CER -Yay installation failed. check install.log"
			exit
		fi
		cd ..
		yay -Suy
	else
		echo -e "$CER - Yay is required for this script, now exiting"
		exit
	fi
fi

### Install all of the above pacakges ####
read -rep $'[\e[1;33mACTION\e[0m] - Would you like to install the packages? (y,n) ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then

    echo -e "$CNT - Installing packages & softwares, this may take a while..."
    for SOFTWR in ${install_stage[@]}; do
        install_software $SOFTWR 
    done

    # Start the bluetooth service
    echo -e "$CNT - Starting the Bluetooth Service..."
    sudo systemctl enable --now bluetooth &>> $INSTLOG
    sleep 2

    # Start the SSH service
    echo -e "$CNT - Starting the SSH Service..."
    sudo systemctl enable sshd &>> $INSTLOG
    sleep 2

   # Enable the sddm login manager service
    echo -e "$CNT - Enabling the SDDM Service..."
    sudo systemctl enable sddm &>> $INSTLOG
    sleep 2
fi

### Install Sddm theme
echo -e "$CNT - Installing SDDM theme..."
sudo git clone https://github.com/Keyitdev/sddm-astronaut-theme.git /usr/share/sddm/themes/sddm-astronaut-theme
sudo cp /usr/share/sddm/themes/sddm-astronaut-theme/Fonts/* /usr/share/fonts
sudo cp ~/dotfiles/hyprland/sddm/sddm.conf /etc/sddm.conf
sudo cp ~/dotfiles/hyprland/sddm/theme.conf /usr/share/sddm/themes/sddm-astronaut-theme/theme.conf
echo -e "$CNT - Sddm theme installation completed."

### Copy Monaco nerd fonts
echo -e "$CNT - Copying Monaco nerd fonts..."
sudo cp ~/dotfiles/hyprland/MonacoFonts/* /usr/share/fonts
echo -e "$CNT - Monaco nerd fonts installation completed."

### Copy samba configure file
echo -e "$CNT - Copying smb.conf..."
sudo cp ~/dotfiles/hyprland/samba/smb.conf /etc/samba/
echo -e "$CNT - Done"

### add user to samba
pdbedit -a rocky

# Start the Samba service
echo -e "$CNT - Starting the Samba Service..."
sudo systemctl enable smb.service nmb.service &>> $INSTLOG
sleep 2

# Setup configs
echo -e "$CNT - Setting up config files..."
ln -s ~/dotfiles/hyprland/hypr ~/.config
ln -s ~/dotfiles/hyprland/mako ~/.config
ln -s ~/dotfiles/hyprland/rofi ~/.config
ln -s ~/dotfiles/hyprland/waybar ~/.config
ln -s ~/dotfiles/hyprland/kitty ~/.config
ln -s ~/dotfiles/hyprland/fish ~/.config
ln -s ~/dotfiles/hyprland/starship.toml ~/.config
ln -s ~/dotfiles/hyprland/.vimrc ~/
echo -e "$CNT - Config files setup completed."

### Change script to exectuable 
chmod +x ~/dotfiles/hyprland/hypr/conf.d/bgaction
chmod +x ~/dotfiles/hyprland/rofi/bin/*
chmod +x ~/dotfiles/hyprland/hypr/hyprlock/*

### Change shell to fishell
chsh -s /usr/bin/fish

### Disable wifi powersave mode ###
read -rep $'[\e[1;33mACTION\e[0m] - Would you like to disable WiFi powersave? (y,n) ' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
    LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
    echo -e "$CNT - The following file has been created $LOC.\n"
    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC &>> $INSTLOG
    echo -en "$CNT - Restarting NetworkManager service, Please wait."
    sleep 2
    sudo systemctl restart NetworkManager &>> $INSTLOG
    
    #wait for services to restore (looking at you DNS)
    for i in {1..6} 
    do
        echo -n "."
        sleep 1
    done
    echo -en "Done!\n"
    sleep 2
    echo -e "\e[1A\e[K$COK - NetworkManager restart completed."
fi

